name: Cypress Tests

on: [push]

env:
  CYPRESS_API_KEY: ${{ secrets.API_KEY }}
  CYPRESS_AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
  CYPRESS_STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}
  CYPRESS_PROJECT_ID: ${{ secrets.PROJECT_ID }}
  CYPRESS_MESSAGING_SENDER_ID: ${{ secrets.MESSAGING_SENDER_ID }}
  CYPRESS_APP_ID: ${{ secrets.APP_ID }}

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: npm i element-plus
      - run: npm i firebase
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm run dev

