name: Unit tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  VITE_API_KEY: ${{ secrets.API_KEY }}
  VITE_AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
  VITE_STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}
  VITE_PROJECT_ID: ${{ secrets.PROJECT_ID }}
  VITE_MESSAGING_SENDER_ID: ${{ secrets.MESSAGING_SENDER_ID }}
  VITE_APP_ID: ${{ secrets.APP_ID }}

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i element-plus
    - run: npm i firebase
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
